# Development Profile Configuration

# JPA / Hibernate Config for Development
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Springdoc / Swagger Configuration for Dev
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
