package com.example.crm.activity.entity;

public enum ActivityType {
    CUSTOMER_CREATED,
    CUSTOMER_UPDATED,
    ADDRESS_ADDED,
    ADDRESS_UPDATED,
    ADDRESS_DELETED,
    TICKET_CREATED,
    TICKET_ASSIGNED,
    TICKET_STARTED,
    TICKET_RESOLVED,
    TICKET_REOPENED,
    TICKET_CLOSED,
    TICKET_PRIORITY_CHANGED,
    TICKET_STATUS_CHANGED
}
